# Generated by Powerlevel10k configuration wizard on 2024-01-01 at 00:00:00 UTC.
# Enhanced for BLUX10K v4.0.0 - Professional Terminal Configuration
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh.
#
# Repository: https://github.com/romkatv/powerlevel10k
# BLUX10K: https://github.com/Justadudeinspace/blux10k
#
# Version: 4.0.0
# Features:
#   - Performance optimized segments
#   - Context-aware styling
#   - Enhanced debugging support
#   - Integrated with BLUX10K ecosystem
#   - Dynamic element loading

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  autoload -Uz is-at-least && is-at-least 5.1 || return

  # ===========================================================================
  # DYNAMIC PROMPT ELEMENTS - LOADED BASED ON CONTEXT
  # ===========================================================================
  
  # Core elements always shown
  local core_left_elements=(
    # =========================[ Line #1 ]=========================
    context                   # user@hostname
    dir                       # current directory
    vcs                       # git status
    virtualenv                # python virtual environment
    command_execution_time    # previous command duration
    # =========================[ Line #2 ]=========================
    newline                   # \n
    prompt_char               # prompt symbol
  )

  local core_right_elements=(
    status                    # exit code of the last command
    background_jobs           # presence of background jobs
    time                      # current time
    battery                   # battery level
    os_icon                   # operating system icon
  )

  # Context-aware elements (added dynamically)
  local context_elements=()

  # Add Docker context if in Docker project
  if [[ -f "Dockerfile" || -f "docker-compose.yml" || -f ".dockerignore" ]]; then
    context_elements+=(blux_docker_context)
  fi

  # Add Kubernetes context if in k8s project
  if [[ -d "k8s" || -f "kustomization.yaml" || -n $(print -l *.yaml(N)) ]]; then
    context_elements+=(blux_k8s_context)
  fi

  # Add Node.js version if package.json exists
  if [[ -f "package.json" ]]; then
    context_elements+=(blux_node_version)
  fi

  # Add Python version if requirements.txt exists
  if [[ -f "requirements.txt" || -f "pyproject.toml" || -f "setup.py" ]]; then
    context_elements+=(blux_python_version)
  fi

  # Add Rust version if Cargo.toml exists
  if [[ -f "Cargo.toml" ]]; then
    context_elements+=(blux_rust_version)
  fi

  # Add Go version if go.mod exists
  if [[ -f "go.mod" ]]; then
    context_elements+=(blux_go_version)
  fi

  # Add BLUX10K status if in development mode
  if [[ -n "$BLUX10K_DEBUG" || -n "$ZSH_DEBUG" ]]; then
    context_elements=(blux10k_status $context_elements)
  fi

  # Final element arrays
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=($core_left_elements)
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=($core_right_elements $context_elements)

  # ===========================================================================
  # PERFORMANCE OPTIMIZATIONS
  # ===========================================================================
  typeset -g POWERLEVEL9K_DISABLE_GITSTATUS=false
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  
  # Async loading
  typeset -g POWERLEVEL9K_VCS_ASYNC=true
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_ASYNC=true
  
  # Disable slow features when terminal is small
  if (( COLUMNS < 80 )); then
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/background_jobs})
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/battery})
  fi

  # ===========================================================================
  # VISUAL STYLING - BLUX10K THEME
  # ===========================================================================
  
  # Basic style options.
  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no surrounding whitespace
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # separate segments with a space
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no end-of-line symbol

  # Color scheme and design for BLUX10K.
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  
  # Enable hyperlinks in directory segment
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=true

  # ===========================================================================
  # SEGMENT CONFIGURATIONS
  # ===========================================================================

  # Context segment configuration.
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=7
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=3
  typeset -g POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE='%n@%m'
  
  # Show SSH icon when connected via SSH
  if [[ -n "$SSH_CONNECTION" ]]; then
    typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m 🔐'
  fi

  # Directory segment configuration.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=0
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=4
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=6
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_DIR_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_DIR_SHORTEN_DELIMITER=''
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=true
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_DIR_HYPERLINK_COLOR=4
  
  # Directory coloring based on depth
  typeset -g POWERLEVEL9K_DIR_DIRNAME_LEVELS_FOREGROUND=(
    4  # level 1
    12 # level 2
    6  # level 3
    13 # level 4
    5  # level 5+
  )

  # VCS (Git) segment configuration.
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=2
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=9
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=8
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
  typeset -g POWERLEVEL9K_VCS_TAG_ICON='\uF412'
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\uF417'
  typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408'
  typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON='\uF296'
  typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON='\uF171'
  typeset -g POWERLEVEL9K_VCS_GIT_ICON='\uF1D3'
  
  # Enable VCS stash indicator
  typeset -g POWERLEVEL9K_VCS_STASH_ICON='\uF01C'

  # Virtualenv segment configuration.
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=6
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=0
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  typeset -g POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER='('
  typeset -g POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=')'
  typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='🐍'

  # Command execution time segment configuration.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  
  # Show execution time in different colors based on duration
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND_EXECUTION_TIME=(
    2  # < 1 min: green
    3  # 1-5 min: yellow
    1  # > 5 min: red
  )

  # Status segment configuration.
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=9
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=9
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'

  # Background jobs segment configuration.
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=5
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=0
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⚙'

  # Time segment configuration.
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=7
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=0
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
  typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''

  # Battery segment configuration.
  typeset -g POWERLEVEL9K_BATTERY_FOREGROUND=7
  typeset -g POWERLEVEL9K_BATTERY_BACKGROUND=0
  typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
  typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=9
  typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=2
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=3
  typeset -g POWERLEVEL9K_BATTERY_STAGES='\uf58d\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'

  # OS icon segment configuration.
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=7
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=0
  
  # Platform-specific icons
  case "$(uname)" in
    Darwin)
      typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''
      ;;
    Linux)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''  # WSL
      else
        typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''  # Linux
      fi
      ;;
    *)
      typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''
      ;;
  esac

  # Prompt character configuration.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=4
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=9
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_LEFT_WHITESPACE=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_RIGHT_WHITESPACE=''
  
  # Context-aware prompt character
  if [[ -n "$BLUX10K_DEBUG" ]]; then
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=3  # Yellow for debug
    typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='🔧'
  elif [[ -n "$VIRTUAL_ENV" ]]; then
    typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='🐍'
  elif git rev-parse --git-dir > /dev/null 2>&1; then
    typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='🅑'
  else
    typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='➜'
  fi

  # ===========================================================================
  # ADVANCED CONFIGURATION
  # ===========================================================================
  
  # Transient prompt configuration.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  
  # Instant prompt customization
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
  typeset -g POWERLEVEL9K_INSTANT_PROMPT_FORCE_FIRST_COMMAND_EXECUTION=false

  # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false
  
  # Gitstatus configuration
  typeset -g POWERLEVEL9K_GITSTATUS_DIR="$HOME/.cache/gitstatus"
  
  # Icon overrides for better visibility
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VCS_VISUAL_IDENTIFIER// }'
  typeset -g POWERLEVEL9K_VCS_GIT_ICON=''
  typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
  typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
  typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''

  # ===========================================================================
  # BLUX10K CUSTOM SEGMENTS
  # ===========================================================================
  
  # Custom segment: BLUX10K Status
  typeset -g POWERLEVEL9K_BLUX10K_STATUS_FOREGROUND=4
  typeset -g POWERLEVEL9K_BLUX10K_STATUS_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX10K_STATUS_CONTENT_EXPANSION='🅑 BLUX10K'

  # Custom segment: Docker Context
  typeset -g POWERLEVEL9K_BLUX_DOCKER_CONTEXT_FOREGROUND=6
  typeset -g POWERLEVEL9K_BLUX_DOCKER_CONTEXT_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX_DOCKER_CONTEXT_VISUAL_IDENTIFIER_EXPANSION='🐳'

  # Custom segment: Kubernetes Context
  typeset -g POWERLEVEL9K_BLUX_K8S_CONTEXT_FOREGROUND=5
  typeset -g POWERLEVEL9K_BLUX_K8S_CONTEXT_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX_K8S_CONTEXT_VISUAL_IDENTIFIER_EXPANSION='⎈'

  # Custom segment: Node.js Version
  typeset -g POWERLEVEL9K_BLUX_NODE_VERSION_FOREGROUND=2
  typeset -g POWERLEVEL9K_BLUX_NODE_VERSION_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION='⬢'

  # Custom segment: Python Version
  typeset -g POWERLEVEL9K_BLUX_PYTHON_VERSION_FOREGROUND=3
  typeset -g POWERLEVEL9K_BLUX_PYTHON_VERSION_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX_PYTHON_VERSION_VISUAL_IDENTIFIER_EXPANSION='🐍'

  # Custom segment: Rust Version
  typeset -g POWERLEVEL9K_BLUX_RUST_VERSION_FOREGROUND=1
  typeset -g POWERLEVEL9K_BLUX_RUST_VERSION_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX_RUST_VERSION_VISUAL_IDENTIFIER_EXPANSION='🦀'

  # Custom segment: Go Version
  typeset -g POWERLEVEL9K_BLUX_GO_VERSION_FOREGROUND=6
  typeset -g POWERLEVEL9K_BLUX_GO_VERSION_BACKGROUND=0
  typeset -g POWERLEVEL9K_BLUX_GO_VERSION_VISUAL_IDENTIFIER_EXPANSION='🐹'

  # If p10k is already loaded, reload configuration.
  (( ! $+functions[p10k] )) || p10k reload
}

# ===========================================================================
# CUSTOM FUNCTIONS FOR BLUX10K SEGMENTS
# ===========================================================================

# Custom segment to show BLUX10K status
function prompt_blux10k_status() {
    local content='🅑 BLUX10K'
    
    if [[ -n "$BLUX10K_DEBUG" ]]; then
        content='🅑 DEBUG'
        p10k segment -b 1 -f 3 -t "$content"
    elif [[ -n "$ZSH_DEBUG" ]]; then
        content='🅑 PROFILE'
        p10k segment -b 1 -f 3 -t "$content"
    else
        p10k segment -b 0 -f 4 -t "$content"
    fi
}

# Custom segment for showing current Docker context
function prompt_blux_docker_context() {
    if command -v docker >/dev/null 2>&1; then
        local context=$(docker context show 2>/dev/null)
        if [[ -n "$context" && "$context" != "default" ]]; then
            local icon='🐳'
            local color=6  # Cyan
            
            # Color coding based on context
            case "$context" in
                *prod*|*production*)
                    color=1  # Red for production
                    ;;
                *stag*|*staging*)
                    color=3  # Yellow for staging
                    ;;
                *dev*|*development*)
                    color=2  # Green for development
                    ;;
                *test*)
                    color=5  # Magenta for test
                    ;;
            esac
            
            p10k segment -b 0 -f $color -i "$icon" -t "$context"
        fi
    fi
}

# Custom segment for showing current Kubernetes context
function prompt_blux_k8s_context() {
    if command -v kubectl >/dev/null 2>&1; then
        local context=$(kubectl config current-context 2>/dev/null)
        if [[ -n "$context" ]]; then
            local icon='⎈'
            local color=5  # Magenta
            
            # Color coding based on context
            case "$context" in
                *prod*|*production*)
                    color=1  # Red for production
                    ;;
                *stag*|*staging*)
                    color=3  # Yellow for staging
                    ;;
                *dev*|*development*)
                    color=2  # Green for development
                    ;;
                *minikube*|*docker-desktop*)
                    color=6  # Cyan for local
                    ;;
            esac
            
            p10k segment -b 0 -f $color -i "$icon" -t "$context"
        fi
    fi
}

# Custom segment for Node.js version (context-aware)
function prompt_blux_node_version() {
    if [[ -f "package.json" ]] || [[ -n "$NVM_BIN" ]] || command -v node >/dev/null 2>&1; then
        local node_version
        if command -v node >/dev/null 2>&1; then
            node_version=$(node --version 2>/dev/null | sed 's/v//')
        fi
        
        if [[ -n "$node_version" ]]; then
            p10k segment -b 0 -f 2 -i '⬢' -t "$node_version"
        fi
    fi
}

# Custom segment for Python version (alternative to virtualenv)
function prompt_blux_python_version() {
    if [[ -f "requirements.txt" ]] || [[ -f "pyproject.toml" ]] || [[ -f "setup.py" ]] || command -v python3 >/dev/null 2>&1; then
        local python_version
        if command -v python3 >/dev/null 2>&1; then
            python_version=$(python3 --version 2>/dev/null | cut -d' ' -f2)
        fi
        
        if [[ -n "$python_version" && -z "$VIRTUAL_ENV" ]]; then
            p10k segment -b 0 -f 3 -i '🐍' -t "$python_version"
        fi
    fi
}

# Custom segment for Rust version
function prompt_blux_rust_version() {
    if [[ -f "Cargo.toml" ]] || command -v rustc >/dev/null 2>&1; then
        local rust_version
        if command -v rustc >/dev/null 2>&1; then
            rust_version=$(rustc --version 2>/dev/null | cut -d' ' -f2)
        fi
        
        if [[ -n "$rust_version" ]]; then
            p10k segment -b 0 -f 1 -i '🦀' -t "$rust_version"
        fi
    fi
}

# Custom segment for Go version
function prompt_blux_go_version() {
    if [[ -f "go.mod" ]] || command -v go >/dev/null 2>&1; then
        local go_version
        if command -v go >/dev/null 2>&1; then
            go_version=$(go version 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i ~ /^go[0-9]/) {sub(/^go/, "", $i); print $i; exit}}')
        fi
        
        if [[ -n "$go_version" ]]; then
            p10k segment -b 0 -f 6 -i '🐹' -t "$go_version"
        fi
    fi
}

# Enhanced VCS status with stash indicator
function +vi-git-stash() {
    if [[ -s ${hook_com[git_root]}/.git/refs/stash ]] ; then
        hook_com[stash]='↩'
    fi
}

# ===========================================================================
# UTILITY FUNCTIONS FOR PROMPT MANAGEMENT
# ===========================================================================

# Function to toggle prompt elements (useful for debugging)
function p10k-toggle-elements() {
    if [[ ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[(I)time]} -eq 0 ]]; then
        # Add time to right prompt
        POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(time)
        echo "Time display enabled"
    else
        # Remove time from right prompt
        POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/time})
        echo "Time display disabled"
    fi
    
    # Toggle battery on laptops
    if [[ "$(uname)" == "Darwin" ]] || grep -qi "battery" /sys/class/power_supply/*/type 2>/dev/null; then
        if [[ ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[(I)battery]} -eq 0 ]]; then
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(battery)
            echo "Battery display enabled"
        else
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/battery})
            echo "Battery display disabled"
        fi
    fi
    
    p10k reload
    echo "Prompt elements updated"
}

# Function to switch between prompt styles
function p10k-switch-style() {
    local style=${1:-blux10k}
    
    case $style in
        lean|minimal)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
            POWERLEVEL9K_DIR_MAX_LENGTH=40
            echo "Switched to minimal style"
            ;;
            
        standard|default)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time battery)
            POWERLEVEL9K_DIR_MAX_LENGTH=60
            echo "Switched to standard style"
            ;;
            
        detailed|full)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv command_execution_time newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time battery os_icon)
            POWERLEVEL9K_DIR_MAX_LENGTH=80
            echo "Switched to detailed style"
            ;;
            
        blux10k|blux)
            # BLUX10K custom style
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv command_execution_time newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time battery os_icon)
            POWERLEVEL9K_DIR_MAX_LENGTH=80
            
            # Custom colors for BLUX10K
            POWERLEVEL9K_DIR_BACKGROUND=4
            POWERLEVEL9K_DIR_FOREGROUND=0
            POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
            POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
            POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=4
            echo "Switched to BLUX10K style"
            ;;
            
        debug)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(blux10k_status context dir vcs virtualenv command_execution_time newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time battery os_icon)
            POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=3
            echo "Switched to debug style"
            ;;
            
        *)
            echo "Available styles: lean, standard, detailed, blux10k, debug"
            echo "Current style:"
            p10k-show-config
            return 1
            ;;
    esac
    
    p10k reload
}

# Aliases for quick prompt style switching
alias p10k-lean='p10k-switch-style lean'
alias p10k-standard='p10k-switch-style standard'
alias p10k-detailed='p10k-switch-style detailed'
alias p10k-blux='p10k-switch-style blux10k'
alias p10k-debug='p10k-switch-style debug'

# Function to show current Powerlevel10k configuration
function p10k-show-config() {
    echo "=== POWERLEVEL10K CONFIGURATION ==="
    echo ""
    echo "Left Prompt Elements:"
    for element in $POWERLEVEL9K_LEFT_PROMPT_ELEMENTS; do
        echo "  • $element"
    done
    echo ""
    echo "Right Prompt Elements:"
    for element in $POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS; do
        echo "  • $element"
    done
    echo ""
    echo "Performance Settings:"
    echo "  • VCS Async: $POWERLEVEL9K_VCS_ASYNC"
    echo "  • Command Time Async: $POWERLEVEL9K_COMMAND_EXECUTION_TIME_ASYNC"
    echo "  • Dir Max Length: $POWERLEVEL9K_DIR_MAX_LENGTH"
    echo ""
    echo "Use 'p10k-switch-style <style>' to change styles"
    echo "Use 'p10k-toggle-elements' to toggle elements"
}

# Enhanced prompt character with custom symbols based on context
function blux10k_prompt_char() {
    local symbol='➜'
    local color=4  # Blue
    
    if [[ -n "$BLUX10K_DEBUG" ]]; then
        symbol='🔧'
        color=3  # Yellow
    elif [[ -n "$ZSH_DEBUG" ]]; then
        symbol='📊'
        color=3  # Yellow
    elif [[ -n "$VIRTUAL_ENV" ]]; then
        symbol='🐍'
        color=6  # Cyan
    elif git rev-parse --git-dir > /dev/null 2>&1; then
        symbol='🅑'
        color=2  # Green
    elif [[ -f "Dockerfile" || -f "docker-compose.yml" ]]; then
        symbol='🐳'
        color=6  # Cyan
    elif [[ -f "package.json" ]]; then
        symbol='⬢'
        color=2  # Green
    fi
    
    p10k segment -f $color -t "$symbol"
}

# Optional: Uncomment to use custom prompt character
# typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERRIDE=true
# typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[-1]='blux10k_prompt_char'

# ===========================================================================
# BLUX10K INTEGRATION WITH HELP SYSTEM
# ===========================================================================

# BLUX10K Powerlevel10k Integration with b10k help system
function p10k-help() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║                   POWERLEVEL10K v4.0.0                         ║"
    echo "║                    BLUX10K Enhanced Integration                ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ PROMPT STYLES ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  p10k-lean                    - Minimal prompt (dir, vcs)"
    echo "  p10k-standard                - Standard prompt with context"
    echo "  p10k-detailed                - Detailed prompt with all elements"
    echo "  p10k-blux                    - BLUX10K custom style"
    echo "  p10k-debug                   - Debug style with BLUX10K status"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ CONFIGURATION ▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  p10k configure               - Run configuration wizard"
    echo "  p10k reload                  - Reload prompt configuration"
    echo "  p10k-show-config             - Show current configuration"
    echo "  p10k-toggle-elements         - Toggle time/battery display"
    echo "  p10k-switch-style <style>    - Switch between prompt styles"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ PROMPT ELEMENTS ▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  context                      - user@hostname (SSH indicator)"
    echo "  dir                          - current directory (hyperlinked)"
    echo "  vcs                          - git status with stash indicator"
    echo "  virtualenv                   - python virtual environment"
    echo "  command_execution_time       - colored by duration"
    echo "  status                       - exit code with icon"
    echo "  background_jobs              - background jobs indicator"
    echo "  time                         - current time"
    echo "  battery                      - battery level with stages"
    echo "  os_icon                      - OS-specific icon"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ CUSTOM SEGMENTS ▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  blux10k_status               - BLUX10K system status"
    echo "  blux_docker_context          - Docker context (colored)"
    echo "  blux_k8s_context             - K8s context (colored)"
    echo "  blux_node_version            - Node.js version"
    echo "  blux_python_version          - Python version"
    echo "  blux_rust_version            - Rust version"
    echo "  blux_go_version              - Go version"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ PERFORMANCE ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  • Async VCS loading"
    echo "  • Dynamic element loading"
    echo "  • Context-aware segments"
    echo "  • Terminal size optimization"
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║        Use 'p10k configure' to customize interactively        ║"
    echo "║        Run 'b10k --help' for full BLUX10K reference           ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
}

# Add p10k-help to b10k system
function b10k() {
    case "$1" in
        p10k|powerlevel10k|prompt)
            shift
            p10k-help
            ;;
        # ... rest of your existing b10k function
    esac
}

# Function to profile prompt rendering
function p10k-profile() {
    local iterations=${1:-100}
    echo "Profiling prompt rendering ($iterations iterations)..."
    
    local start_time=$((EPOCHREALTIME*1000))
    for ((i=1; i<=iterations; i++)); do
        print -P "$PROMPT" >/dev/null
    done
    local end_time=$((EPOCHREALTIME*1000))
    
    local total_time=$((end_time - start_time))
    local avg_time=$((total_time / iterations))
    
    echo "Total time: ${total_time}ms"
    echo "Average per prompt: ${avg_time}ms"
    echo "Performance: $((1000 / avg_time)) prompts/second"
}

# ===========================================================================
# FINAL INITIALIZATION
# ===========================================================================

# Tell Powerlevel10k to reload configuration when user configuration changes.
(( ! $+functions[p10k] )) || p10k reload

# Final configuration validation and optimization
if (( $+functions[p10k] )); then
    # Enable instant prompt if available
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi
    
    # Finalize p10k configuration
    p10k finalize
    
    # Performance optimization for slow systems
    if [[ "$(uname)" == "Darwin" ]] || [[ "$(uname -m)" == "arm"* ]]; then
        # Disable some animations on ARM/Mac for better performance
        typeset -g POWERLEVEL9K_VCS_ASYNC=false
        typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=60
    fi
    
    # Debug mode optimizations
    if [[ -n "$BLUX10K_DEBUG" ]]; then
        echo "[P10K] Configuration loaded in debug mode"
        echo "[P10K] Left elements: ${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[@]}"
        echo "[P10K] Right elements: ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]}"
    fi
    
else
    echo "Powerlevel10k not loaded. BLUX10K will use fallback prompt."
    echo "Install with: zinit ice depth=1; zinit light romkatv/powerlevel10k"
    
    # Fallback simple prompt
    PROMPT='%F{4}%n@%m%f:%F{2}%~%f %# '
    RPROMPT='%F{3}%*%f'
fi

# ===========================================================================
# ENVIRONMENT-SPECIFIC OVERRIDES
# ===========================================================================

# Override settings in specific environments
case "$(uname)" in
    Darwin)
        # macOS specific optimizations
        typeset -g POWERLEVEL9K_BATTERY_STAGES='\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
        ;;
    Linux)
        # Linux/WSL optimizations
        if grep -qi microsoft /proc/version 2>/dev/null; then
            # WSL specific
            typeset -g POWERLEVEL9K_DIR_HYPERLINK=false  # Hyperlinks don't work well in WSL
        fi
        ;;
esac

# SSH session optimizations
if [[ -n "$SSH_CONNECTION" ]]; then
    # Simplify prompt over SSH for better performance
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/battery})
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/os_icon})
    POWERLEVEL9K_DIR_MAX_LENGTH=40
fi

# Small terminal optimizations
if (( COLUMNS < 80 )); then
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs newline prompt_char)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
fi

# Export configuration version
export BLUX10K_P10K_VERSION="4.0.0"
