# Generated by Powerlevel10k configuration wizard on 2024-01-01 at 00:00:00 UTC.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh.
# Config file for Powerlevel10k with customizations for BLUX10K.
#
# Repository: https://github.com/romkatv/powerlevel10k
# BLUX10K: https://github.com/Justadudeinspace/blux10k
#
# Installation instructions:
#   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
#   echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  autoload -Uz is-at-least && is-at-least 5.1 || return

  # Left prompt segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    context                   # user@hostname
    dir                       # current directory
    vcs                       # git status
    virtualenv                # python virtual environment
    command_execution_time    # previous command duration
    # =========================[ Line #2 ]=========================
    newline                   # \n
    prompt_char               # prompt symbol
  )

  # Right prompt segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                    # exit code of the last command
    background_jobs           # presence of background jobs
    time                      # current time
    battery                   # battery level
    os_icon                   # operating system icon
  )

  # Basic style options.
  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no surrounding whitespace
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # separate segments with a space
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no end-of-line symbol

  # Color scheme and design for BLUX10K.
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete

  # Context segment configuration.
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=7
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'

  # Directory segment configuration.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=0
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=4
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=6
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_DIR_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_DIR_SHORTEN_DELIMITER=''
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false

  # VCS (Git) segment configuration.
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=2
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=9
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=8
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=0
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
  typeset -g POWERLEVEL9K_VCS_TAG_ICON='\uF412'
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\uF417'
  typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408'
  typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON='\uF296'
  typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON='\uF171'

  # Virtualenv segment configuration.
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=6
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=0
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  typeset -g POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER='('
  typeset -g POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=')'

  # Command execution time segment configuration.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # Status segment configuration.
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=9
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=9
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0

  # Background jobs segment configuration.
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=5
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=0
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true

  # Time segment configuration.
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=7
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=0
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Battery segment configuration.
  typeset -g POWERLEVEL9K_BATTERY_FOREGROUND=7
  typeset -g POWERLEVEL9K_BATTERY_BACKGROUND=0
  typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
  typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=9
  typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=2
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=3

  # OS icon segment configuration.
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=7
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=0

  # Prompt character configuration.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=4
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=9
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''

  # Transient prompt configuration.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell Powerlevel10k to reload configuration when user configuration changes.
(( ! $+functions[p10k] )) || p10k reload

# BLUX10K Custom Powerlevel10k Functions and Enhancements

# Custom segment to show BLUX10K status
function prompt_blux10k_status() {
    p10k segment -b 0 -f 4 -i '🅑' -t 'BLUX10K'
}

# Custom segment for showing current Kubernetes context (if available)
function prompt_k8s_context() {
    if command -v kubectl >/dev/null 2>&1; then
        local context=$(kubectl config current-context 2>/dev/null)
        if [[ -n "$context" ]]; then
            p10k segment -b 3 -f 7 -i '⎈' -t "$context"
        fi
    fi
}

# Custom segment for Docker context
function prompt_docker_context() {
    if command -v docker >/dev/null 2>&1; then
        local context=$(docker context show 2>/dev/null)
        if [[ -n "$context" && "$context" != "default" ]]; then
            p10k segment -b 4 -f 7 -i '🐳' -t "$context"
        fi
    fi
}

# Custom segment for Node.js version
function prompt_node_version() {
    if command -v node >/dev/null 2>&1; then
        local node_version=$(node --version 2>/dev/null | sed 's/v//')
        if [[ -n "$node_version" ]]; then
            p10k segment -b 2 -f 0 -i '⬢' -t "$node_version"
        fi
    fi
}

# Custom segment for Python version (alternative to virtualenv)
function prompt_python_version() {
    if command -v python3 >/dev/null 2>&1; then
        local python_version=$(python3 --version 2>/dev/null | cut -d' ' -f2)
        if [[ -n "$python_version" && -z "$VIRTUAL_ENV" ]]; then
            p10k segment -b 5 -f 0 -i '🐍' -t "$python_version"
        fi
    fi
}

# Enhanced VCS status with more detailed information
function +vi-git-stash() {
    if [[ -s ${hook_com[git_root]}/.git/refs/stash ]] ; then
        hook_com[stash]='↩'
    fi
}

# Function to toggle prompt elements (useful for debugging)
function p10k-toggle-elements() {
    if [[ ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[(I)time]} -eq 0 ]]; then
        # Add time to right prompt
        POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(time)
    else
        # Remove time from right prompt
        POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/time})
    fi
    p10k reload
    echo "Prompt elements toggled. Current right prompt: ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]}"
}

# Function to switch between prompt styles
function p10k-switch-style() {
    local style=$1
    case $style in
        lean|minimal)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
            ;;
        standard|default)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time battery)
            ;;
        detailed|full)
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv command_execution_time newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time battery os_icon)
            ;;
        blux10k|blux)
            # BLUX10K custom style
            POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv command_execution_time newline prompt_char)
            POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time battery os_icon)
            # Custom colors for BLUX10K
            POWERLEVEL9K_DIR_BACKGROUND=4
            POWERLEVEL9K_DIR_FOREGROUND=0
            POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
            POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
            ;;
        *)
            echo "Available styles: lean, standard, detailed, blux10k"
            return 1
            ;;
    esac
    p10k reload
    echo "Switched to $style style"
}

# Aliases for quick prompt style switching
alias p10k-lean='p10k-switch-style lean'
alias p10k-standard='p10k-switch-style standard'
alias p10k-detailed='p10k-switch-style detailed'
alias p10k-blux='p10k-switch-style blux10k'

# Function to show current Powerlevel10k configuration
function p10k-show-config() {
    echo "Left Prompt Elements: ${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[@]}"
    echo "Right Prompt Elements: ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]}"
    echo "Current Style:"
    p10k display
}

# Enhanced prompt character with custom symbols
function blux10k_prompt_char() {
    if [[ -n "$BLUX10K_DEBUG" ]]; then
        p10k segment -f 1 -t '🔧'
    elif [[ -n "$VIRTUAL_ENV" ]]; then
        p10k segment -f 6 -t '🐍'
    elif git rev-parse --git-dir > /dev/null 2>&1; then
        p10k segment -f 2 -t '🅑'
    else
        p10k segment -f 4 -t '➜'
    fi
}

# Optional: Uncomment to use custom prompt character
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[-1]='blux10k_prompt_char'

# BLUX10K Powerlevel10k Integration with b10k help system
function p10k-help() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║                   POWERLEVEL10K COMMANDS                       ║"
    echo "║                    BLUX10K Integration                         ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ PROMPT STYLES ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  p10k-lean                    - Minimal prompt (dir, vcs, prompt)"
    echo "  p10k-standard                - Standard prompt with context"
    echo "  p10k-detailed                - Detailed prompt with all elements"
    echo "  p10k-blux                    - BLUX10K custom style"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ CONFIGURATION ▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  p10k configure               - Run configuration wizard"
    echo "  p10k reload                  - Reload prompt configuration"
    echo "  p10k-show-config             - Show current configuration"
    echo "  p10k-toggle-elements         - Toggle time display"
    echo ""
    echo "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ PROMPT ELEMENTS ▬▬▬▬▬▬▬▬▬▬▬▬▬"
    echo "  context                      - user@hostname"
    echo "  dir                          - current directory"
    echo "  vcs                          - git status"
    echo "  virtualenv                   - python virtual environment"
    echo "  command_execution_time       - previous command duration"
    echo "  status                       - exit code"
    echo "  background_jobs              - background jobs"
    echo "  time                         - current time"
    echo "  battery                      - battery level"
    echo "  os_icon                      - OS icon"
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║        Use 'p10k configure' to customize interactively        ║"
    echo "║        Run 'b10k --help' for full BLUX10K reference           ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
}

# Add p10k-help to b10k system
function b10k() {
    case "$1" in
        p10k|powerlevel10k)
            p10k-help
            ;;
        # ... rest of your existing b10k function
    esac
}

# Final configuration validation
if (( $+functions[p10k] )); then
    p10k finalize
else
    echo "Powerlevel10k not loaded. Run: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k"
    echo "Then add: source ~/powerlevel10k/powerlevel10k.zsh-theme to your .zshrc"
fi